### ISSUE TITLE
Crash on parameters

### ISSUE THREAD

**Issue by dayanithi06** [Fotoapparat/Fotoapparat#1]
When there is no flash support in mobile it crashes.

java.lang.NullPointerException
                                                                           at io.fotoapparat.hardware.v1.capabilities.CapabilitiesFactory.extractFlashModes(CapabilitiesFactory.java:57)
                                                                           at io.fotoapparat.hardware.v1.capabilities.CapabilitiesFactory.fromParameters(CapabilitiesFactory.java:29)
                                                                           at io.fotoapparat.hardware.v1.Camera1.getCapabilities(Camera1.java:187)

**Comment by dmitry-zaitsev** [comment]
@dayanithi06 Thanks for reporting!

It should be fixed now.
