### ISSUE TITLE
Front Camera still crash

### ISSUE THREAD

**Issue by shivam2702** [Fotoapparat/Fotoapparat#10]
fotoapparat = Fotoapparat
                .with(this)
                .into(cameraView)
                .photoSize(standardRatio(biggestSize()))
                .previewSize(standardRatio(biggestSize()))
                .lensPosition(front())
                .focusMode(firstAvailable(
                        continuousFocus(),
                        autoFocus(),
                        fixed()
                ))
                .flash(firstAvailable(
                        autoRedEye(),
                        autoFlash(),
                        torch()
                ))
                .logger(loggers(
                        logcat(),
                        fileLogger(this)
                ))
                .build();

PID: 25731
                                                             java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Requested to set the exposure mode but the flash mode has not been provided.
                                                                 at io.fotoapparat.result.PendingResult.getResultUnsafe(PendingResult.java:118)
                                                                 at io.fotoapparat.result.PendingResult.access$100(PendingResult.java:20)
                                                                 at io.fotoapparat.result.PendingResult$2.run(PendingResult.java:97)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Requested to set the exposure mode but the flash mode has not been provided.
                                                                 at java.util.concurrent.FutureTask.report(FutureTask.java:94)
                                                                 at java.util.concurrent.FutureTask.get(FutureTask.java:164)
                                                                 at io.fotoapparat.result.PendingResult.getResultUnsafe(PendingResult.java:116)
                                                                 at io.fotoapparat.result.PendingResult.access$100(PendingResult.java:20) 
                                                                 at io.fotoapparat.result.PendingResult$2.run(PendingResult.java:97) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
                                                              Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Requested to set the exposure mode but the flash mode has not been provided.
                                                                 at java.util.concurrent.FutureTask.report(FutureTask.java:94)
                                                                 at java.util.concurrent.FutureTask.get(FutureTask.java:164)
                                                                 at io.fotoapparat.result.PendingResult$1.call(PendingResult.java:56)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
                                                              Caused by: java.lang.IllegalStateException: Requested to set the exposure mode but the flash mode has not been provided.
                                                                 at io.fotoapparat.hardware.v2.parameters.CaptureRequestBuilder.validate(CaptureRequestBuilder.java:113)
                                                                 at io.fotoapparat.hardware.v2.parameters.CaptureRequestBuilder.build(CaptureRequestBuilder.java:103)
                                                                 at io.fotoapparat.hardware.v2.parameters.CaptureRequestFactory.createCaptureRequest(CaptureRequestFactory.java:129)
                                                                 at io.fotoapparat.hardware.v2.lens.operations.LensOperationsFactory.createCaptureOperation(LensOperationsFactory.java:83)
                                                                 at io.fotoapparat.hardware.v2.lens.executors.CaptureExecutor.takePicture(CaptureExecutor.java:27)
                                                                 at io.fotoapparat.hardware.v2.Camera2.takePicture(Camera2.java:151)
                                                                 at io.fotoapparat.routine.TakePictureTask$1.call(TakePictureTask.java:33)
                                                                 at io.fotoapparat.routine.TakePictureTask$1.call(TakePictureTask.java:16)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                 at java.lang.Thread.run(Thread.java:818)

This error was solved when i remove the flash section 

fotoapparat = Fotoapparat
                .with(this)
                .into(cameraView)
                .photoSize(standardRatio(biggestSize()))
                .previewSize(standardRatio(biggestSize()))
                .lensPosition(front())
                .focusMode(firstAvailable(
                        continuousFocus(),
                        autoFocus(),
                        fixed()
                ))
                .logger(loggers(
                        logcat(),
                        fileLogger(this)
                ))
                .build();

So what will happen if some devices have front facing flash....

and can you please provide a method to flip the front face selfie?

**Comment by Diolor** [comment]
Sure it exists, 

```
.flash(firstAvailable(
  autoRedEye(),
  autoFlash(),
  torch(),
  off()  <-- you need this one too
))
```

Just the logs are not explicit. That's why #9  is open :)

**Comment by shivam2702** [comment]
Thanks 👍
