### ISSUE TITLE
Fotoapparat : front flash support

### ISSUE THREAD

**Issue by adilkhalid** [Fotoapparat/Fotoapparat#127]
#### Need to figure out if fotapparat supports front flash. I have not seen anything to indicate that it does, but would be great to see if this is a current feature or future feature. 

Following is the builder code that I am trying to use to turn on flash on front() camera.

```java
Fotoapparat
  .with(context)
  .into(cameraView)          
  .previewScaleType(ScaleType.CENTER_CROP)  
  .photoSize(biggestSize())  
  .lensPosition(front())    
  .flash(firstAvailable(
               autoRedEye(),
               autoFlash(),
               torch(),
               on()))
   .build();

```

#### Recieved the following error:

```java
FATAL EXCEPTION: pool-4-thread-1
Process: com.jnj.safari.tanzania.develop, PID: 19431
 java.lang.IllegalArgumentException: Opened camera does not support the selected flash options.
                                                                                     at io.fotoapparat.parameter.provider.InitialParametersValidator.validateParameter(InitialParametersValidator.java:31)
                                                                                     at io.fotoapparat.parameter.provider.InitialParametersValidator.validate(InitialParametersValidator.java:25)
                                                                                     at io.fotoapparat.parameter.provider.InitialParametersProvider.initialParameters(InitialParametersProvider.java:89)
                                                                                     at io.fotoapparat.routine.StartCameraRoutine.tryToStartCamera(StartCameraRoutine.java:60)
                                                                                     at io.fotoapparat.routine.StartCameraRoutine.run(StartCameraRoutine.java:47)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:762)
10-29 17:30:08.050 19431-19431/com.jnj.safari.tanzania.develop D/ViewRootImpl@362e743[CameraActivity]: MSG_WINDOW_FOCUS_CHANGED 0

```

#### Context:

* *FA version*:
implementation 'io.fotoapparat.fotoapparat:library:1.4.1'
* *Devices/APIs affected*:
Pixel XL API 26

**Comment by Diolor** [comment]
The message you see is correct as in your constructor you always specify **some flash if the hardware** but not the case of no front flash hardware exists.

firstAvailable(
               autoRedEye(),
               autoFlash(),
               torch(),
               on(),
               off() // <- add this line
)
