### ISSUE TITLE
io.fotoapparat.exception.camera.UnsupportedConfigurationException: FocusMode configuration selector couldn't select a value. Supported parameters:

### ISSUE THREAD

**Issue by developer--** [Fotoapparat/Fotoapparat#168]
Switch to front camera crashes app, this happens in sample project.

```
io.fotoapparat.exception.camera.UnsupportedConfigurationException: FocusMode configuration selector couldn't select a value. Supported parameters: [io.fotoapparat.parameter.FocusMode$Auto@b05650d, io.fotoapparat.parameter.FocusMode$Macro@b242cc2, io.fotoapparat.parameter.FocusMode$Infinity@4165ad3, io.fotoapparat.parameter.FocusMode$ContinuousFocusPicture@f632610, io.fotoapparat.parameter.FocusMode$ContinuousFocusVideo@3304509]
                                                                                at io.fotoapparat.parameter.camera.provide.CameraParametersProviderKt.getCameraParameters(CameraParametersProvider.kt:157)
                                                                                at io.fotoapparat.hardware.Device.getCameraParameters(Device.kt:146)
                                                                                at io.fotoapparat.routine.camera.UpdateConfigurationRoutineKt.updateCameraConfiguration(UpdateConfigurationRoutine.kt:25)
                                                                                at io.fotoapparat.routine.camera.StartRoutineKt.start(StartRoutine.kt:39)
                                                                                at io.fotoapparat.routine.camera.SwitchCameraRoutineKt.restartPreview(SwitchCameraRoutine.kt:49)
                                                                                at io.fotoapparat.routine.camera.SwitchCameraRoutineKt.switchCamera(SwitchCameraRoutine.kt:32)
                                                                                at io.fotoapparat.Fotoapparat$switchTo$1.invoke(Fotoapparat.kt:225)
                                                                                at io.fotoapparat.Fotoapparat$switchTo$1.invoke(Fotoapparat.kt:40)
                                                                                at io.fotoapparat.hardware.ExecutorKt$sam$Runnable$ca0b98de.run(Executor.kt)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
```

Lenovo, API 23

**Comment by Diolor** [comment]
For some reason this Lenovo's front camera doesn't support fixed focus. I will add the selector in the sample sometime soon
