### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by FIndustries** [Fotoapparat/Fotoapparat#28]
I get a lot of crashlogs on devices with Android 4.2 and 4.4 (most are Samsung):

```java
java.lang.IllegalArgumentException: 
  at io.fotoapparat.parameter.provider.InitialParametersValidator.validate(c.java:0)
                                                                  validateParameter
  at io.fotoapparat.parameter.provider.InitialParametersValidator.validate(c.java:0)
                                                                  validateParameter
  at io.fotoapparat.parameter.provider.InitialParametersProvider.initialParameters(b.java:0)
                                                                 putPreviewSize
                                                                 photoSize
  at io.fotoapparat.routine.StartCameraRoutine.run(d.java:0)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:841)
```

I'm only using this code:

```java
fotoapparat = Fotoapparat
                    .with(this)
                    .into(cameraView)
                    .lensPosition(front())
                    .build();
```

**Comment by Diolor** [comment]
Hi @FIndustries ! Can you please put the full stacktrace and, if possible, non-obscufied?

**Comment by FIndustries** [comment]
Unfortunately this is what I have.
It's from Google Play Developer Console.

**Comment by dmitry-zaitsev** [comment]
I might have an idea what is the reason being the crash. Will fix it asap and publish a new version.

**Comment by dmitry-zaitsev** [comment]
The issue should be fixed now. Try updating to `1.0.1`.
