### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method Camera.getParameters() on a null object

### ISSUE THREAD

**Issue by fm-eb** [Fotoapparat/Fotoapparat#299]
We get many crashes with the following logcat:

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at io.fotoapparat.result.PendingResult.getResultUnsafe(PendingResult.java:125)
	at io.fotoapparat.result.PendingResult.access$100(PendingResult.java:20)
	at io.fotoapparat.result.PendingResult$2.run(PendingResult.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at io.fotoapparat.result.PendingResult.getResultUnsafe(PendingResult.java:123)
	... 5 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at io.fotoapparat.hardware.v1.Camera1.getCapabilities(Camera1.java:186)
	at io.fotoapparat.parameter.provider.GetCapabilitiesTask$1.call(GetCapabilitiesTask.java:18)
	at io.fotoapparat.parameter.provider.GetCapabilitiesTask$1.call(GetCapabilitiesTask.java:15)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

Meta data for this crash:

```
Android: 8.0.0
Android Build: R16NW.A520FXXU4CRF1
Manufacturer: samsung
Model: SM-A520F
```

**Comment by keshavchouhan18** [comment]
app getting crash with same bug NullPointerException: Attempt to invoke virtual method Camera.getParameters() on a null object
