### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by markGilchristBookingBug** [Fotoapparat/Fotoapparat#30]
I am getting this crash via crashlytics

Fatal Exception: java.util.NoSuchElementException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:789)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at java.util.Collections.max(Collections.java:1626)
       at io.fotoapparat.parameter.selector.SizeSelectors$1.select(SizeSelectors.java:23)
       at io.fotoapparat.parameter.selector.SizeSelectors$1.select(SizeSelectors.java:20)
       at io.fotoapparat.parameter.selector.Selectors$2.select(Selectors.java:56)
       at io.fotoapparat.parameter.provider.InitialParametersProvider.putPreviewSize(InitialParametersProvider.java:67)
       at io.fotoapparat.parameter.provider.InitialParametersProvider.initialParameters(InitialParametersProvider.java:48)
       at io.fotoapparat.routine.StartCameraRoutine.run(StartCameraRoutine.java:41)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by dmitry-zaitsev** [comment]
Which version of the library are you using?

**Comment by markGilchristBookingBug** [comment]
'io.fotoapparat.fotoapparat:library:1.0.0', according to craslytics this has happened only on an htc device, all others work perfectly

**Comment by dmitry-zaitsev** [comment]
This issue was just fixed yesterday and now available in 1.0.1. Please update :)

**Comment by markGilchristBookingBug** [comment]
thanks guys

**Comment by markGilchristBookingBug** [comment]
ATAL EXCEPTION: pool-4-thread-1
                                                                                      Process: com.groundcontrol.apps.android.maint, PID: 24826
                                                                                      java.util.NoSuchElementException
                                                                                          at java.util.HashMap$HashIterator.nextEntry(HashMap.java:789)
                                                                                          at java.util.HashMap$KeyIterator.next(HashMap.java:814)
                                                                                          at java.util.Collections.max(Collections.java:1630)
                                                                                          at io.fotoapparat.parameter.selector.SizeSelectors$1.select(SizeSelectors.java:23)
                                                                                          at io.fotoapparat.parameter.selector.SizeSelectors$1.select(SizeSelectors.java:20)
                                                                                          at io.fotoapparat.parameter.selector.Selectors$2.select(Selectors.java:56)
                                                                                          at io.fotoapparat.parameter.selector.Selectors$1.select(Selectors.java:26)
                                                                                          at io.fotoapparat.parameter.provider.InitialParametersProvider.putPreviewSize(InitialParametersProvider.java:69)
                                                                                          at io.fotoapparat.parameter.provider.InitialParametersProvider.initialParameters(InitialParametersProvider.java:50)
                                                                                          at io.fotoapparat.routine.StartCameraRoutine.run(StartCameraRoutine.java:41)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                          at java.lang.Thread.run(Thread.java:818)
we are still getting this on HTCs in 1.0.1
