### ISSUE TITLE
Error msg like these

### ISSUE THREAD

**Issue by coderYiTaoZhang** [Fotoapparat/Fotoapparat#305]
When i use my app in Devices OppoR17 and Oppo R17 plus , there are some issue happended;  

10-08 14:35:40.575 E/mm-camera-CORE(  679): SN: expTimelimit = 3000000000
10-08 14:35:40.601 E/ImageLoader(22115): UIL doesn't support scheme(protocol) by default [/storage/emulated/0/DCIM/Camera/IMG20181008143540.jpg]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
10-08 14:35:40.601 E/ImageLoader(22115): java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [/storage/emulated/0/DCIM/Camera/IMG20181008143540.jpg]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
10-08 14:35:40.601 E/ImageLoader(22115): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromOtherSource(BaseImageDownloader.java:280)
10-08 14:35:40.601 E/ImageLoader(22115): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:99)
10-08 14:35:40.601 E/ImageLoader(22115): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.downloadImage(LoadAndDisplayImageTask.java:291)
10-08 14:35:40.601 E/ImageLoader(22115): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryCacheImageOnDisk(LoadAndDisplayImageTask.java:274)
10-08 14:35:40.601 E/ImageLoader(22115): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:230)
10-08 14:35:40.601 E/ImageLoader(22115): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:136)
10-08 14:35:40.601 E/ImageLoader(22115): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-08 14:35:40.601 E/ImageLoader(22115): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-08 14:35:40.601 E/ImageLoader(22115): 	at java.lang.Thread.run(Thread.java:764)
10-08 14:35:40.616 D/PwdCheckService(20923): getTopActivityLollipopOnwards(): com.qicai.translate
10-08 14:35:40.646 W/Binder  ( 1677): Outgoing transactions from this process must be FLAG_ONEWAY
10-08 14:35:40.646 W/Binder  ( 1677): java.lang.Throwable
10-08 14:35:40.646 W/Binder  ( 1677): 	at android.os.BinderProxy.transact(Binder.java:752)
10-08 14:35:40.646 W/Binder  ( 1677): 	at android.view.IWindow$Stub$Proxy.isUserDefinedToast(IWindow.java:635)
10-08 14:35:40.646 W/Binder  ( 1677): 	at com.android.server.wm.WindowManagerService.addWindow(WindowManagerService.java:1555)
10-08 14:35:40.646 W/Binder  ( 1677): 	at com.android.server.wm.Session.addToDisplay(Session.java:205)
10-08 14:35:40.646 W/Binder  ( 1677): 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:124)
10-08 14:35:40.646 W/Binder  ( 1677): 	at com.android.server.wm.Session.onTransact(Session.java:166)
10-08 14:35:40.646 W/Binder  ( 1677): 	at android.os.Binder.execTransact(Binder.java:697)
10-08 14:35:40.652 D/ActivityTrigger( 1677): activityResumeTrigger: The activity in ApplicationInfo{a373849 com.qicai.translate} is now in focus and seems to be in full-screen mode

10-08 14:35:03.937 E/mm-camera-CORE(  679): SN: expTimelimit = 3000000000
10-08 14:35:03.941 W/FastPrintWriter( 1677): Write failure
10-08 14:35:03.941 W/FastPrintWriter( 1677): java.io.IOException: write failed: EIO (I/O error)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at libcore.io.IoBridge.write(IoBridge.java:558)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at java.io.FileOutputStream.write(FileOutputStream.java:326)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at com.android.internal.util.FastPrintWriter.flushBytesLocked(FastPrintWriter.java:352)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:375)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at com.android.internal.util.FastPrintWriter.flush(FastPrintWriter.java:410)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at android.os.ShellCommand.exec(ShellCommand.java:118)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at com.android.providers.settings.SettingsService.onShellCommand(Unknown Source:15)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at android.os.Binder.shellCommand(Binder.java:594)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at android.os.Binder.onTransact(Binder.java:492)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at android.os.Binder.execTransact(Binder.java:697)
10-08 14:35:03.941 W/FastPrintWriter( 1677): Caused by: android.system.ErrnoException: write failed: EIO (I/O error)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at libcore.io.Linux.writeBytes(Native Method)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at libcore.io.Linux.write(Linux.java:288)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:345)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	at libcore.io.IoBridge.write(IoBridge.java:553)
10-08 14:35:03.941 W/FastPrintWriter( 1677): 	... 9 more
10-08 14:35:03.945 I/elsa    (11442): addCgroupTask, TASK_PID, add the uid: 2000 pid:22914 to cgroup /dev/cpuset
10-08 14:35:03.963 I/elsa    (11442): addCgroupTask, TASK_PID, add the uid: 2000 pid:22915 to cgroup /dev/cpuset
10-08 14:35:03.984 E/mm-camera-CORE(  679): SN: expTimelimit = 3000000000
10-08 14:35:03.989 W/FastPrintWriter( 1677): Write failure
10-08 14:35:03.989 W/FastPrintWriter( 1677): java.io.IOException: write failed: EIO (I/O error)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at libcore.io.IoBridge.write(IoBridge.java:558)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at java.io.FileOutputStream.write(FileOutputStream.java:326)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at com.android.internal.util.FastPrintWriter.flushBytesLocked(FastPrintWriter.java:352)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:375)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at com.android.internal.util.FastPrintWriter.flush(FastPrintWriter.java:410)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at android.os.ShellCommand.exec(ShellCommand.java:118)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at com.android.providers.settings.SettingsService.onShellCommand(Unknown Source:15)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at android.os.Binder.shellCommand(Binder.java:594)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at android.os.Binder.onTransact(Binder.java:492)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at android.os.Binder.execTransact(Binder.java:697)
10-08 14:35:03.989 W/FastPrintWriter( 1677): Caused by: android.system.ErrnoException: write failed: EIO (I/O error)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at libcore.io.Linux.writeBytes(Native Method)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at libcore.io.Linux.write(Linux.java:288)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:345)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	at libcore.io.IoBridge.write(IoBridge.java:553)
10-08 14:35:03.989 W/FastPrintWriter( 1677): 	... 9 more
10-08 14:35:03.998 I/elsa    (11442): addCgroupTask, TASK_PID, add the uid: 2000 pid:22917 to cgroup /dev/cpuset
10-08 14:35:03.999 I/elsa    (11442): addCgroupTask, TASK_PID, add the uid: 2000 pid:22918 to cgroup /dev/cpuset
10-08 14:35:04.015 D/PwdCheckService(20923): getTopActivityLollipopOnwards(): com.qicai.translate
10-08 14:35:04.022 E/mm-camera-CORE(  679): SN: expTimelimit = 3000000000

**Comment by dmitry-zaitsev** [comment]
Please provide a code snippet where you are trying to load the image.
