### ISSUE TITLE
Crash version 1.0.0

### ISSUE THREAD

**Issue by markGilchristBookingBug** [Fotoapparat/Fotoapparat#31]
Fatal Exception: java.lang.IllegalArgumentException: Opened camera does not support the selected focus_mode options.
       at io.fotoapparat.parameter.provider.InitialParametersValidator.validateParameter(InitialParametersValidator.java:31)
       at io.fotoapparat.parameter.provider.InitialParametersValidator.validate(InitialParametersValidator.java:24)
       at io.fotoapparat.parameter.provider.InitialParametersProvider.initialParameters(InitialParametersProvider.java:52)
       at io.fotoapparat.routine.StartCameraRoutine.run(StartCameraRoutine.java:41)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

I am getting this on 1.0.0, if it now fixed then I am sorry to bother you

**Comment by dmitry-zaitsev** [comment]
Please post here how you are creating Fotoapparat instance.

**Comment by markGilchristBookingBug** [comment]
private void initCamera() {
        if (!checkCameraHardware(getContext()) || isInitialised) return;
        fotoapparat = Fotoapparat
                .with(getContext())
                .into(cameraView)
                .photoSize(biggestSize())
                .lensPosition(back())
                .focusMode( firstAvailable(  // (optional) use the first focus mode which is supported by device
                        continuousFocus(),
                        autoFocus(),         // in case if continuous focus is not available on device, auto focus will be used
                        fixed())             // if even auto focus is not available - fixed focus mode will be used
                )
                .build();
        isInitialised = true;
}

**Comment by dmitry-zaitsev** [comment]
Fixed (hopefully) and should be rolled out in 1.0.2 within a day or two.
