### ISSUE TITLE
NoSuchElementException version 1.0.1

### ISSUE THREAD

**Issue by markGilchristBookingBug** [Fotoapparat/Fotoapparat#32]
we are still getting this on HTCs in 1.0.1
OS Version 6.0
Model Number HTC One_M8

FATAL EXCEPTION: pool-4-thread-1
Process: com.groundcontrol.apps.android.maint, PID: 24826
java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:789)
at java.util.HashMap$KeyIterator.next(HashMap.java:814)
at java.util.Collections.max(Collections.java:1630)
at io.fotoapparat.parameter.selector.SizeSelectors$1.select(SizeSelectors.java:23)
at io.fotoapparat.parameter.selector.SizeSelectors$1.select(SizeSelectors.java:20)
at io.fotoapparat.parameter.selector.Selectors$2.select(Selectors.java:56)
at io.fotoapparat.parameter.selector.Selectors$1.select(Selectors.java:26)
at io.fotoapparat.parameter.provider.InitialParametersProvider.putPreviewSize(InitialParametersProvider.java:69)
at io.fotoapparat.parameter.provider.InitialParametersProvider.initialParameters(InitialParametersProvider.java:50)
at io.fotoapparat.routine.StartCameraRoutine.run(StartCameraRoutine.java:41)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by dmitry-zaitsev** [comment]
Fixed. Will be part of 1.0.2.
