### ISSUE TITLE
ExecutionException: takePicture failed

### ISSUE THREAD

**Issue by ptrbrynt** [Fotoapparat/Fotoapparat#98]
I've been getting this error reported a lot, but only on a Lenovo TB-X103F tablet using the front-facing camera. Not reported on any other devices. Can anything be done at my or your end to catch the error?

```
Fatal Exception: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: takePicture failed
       at io.fotoapparat.result.PendingResult.getResultUnsafe(PendingResult.java:129)
       at io.fotoapparat.result.PendingResult.access$100(PendingResult.java:20)
       at io.fotoapparat.result.PendingResult$2.run(PendingResult.java:98)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: takePicture failed
       at java.util.concurrent.FutureTask.report(FutureTask.java:94)
       at java.util.concurrent.FutureTask.get(FutureTask.java:164)
       at io.fotoapparat.result.PendingResult.getResultUnsafe(PendingResult.java:127)
       at io.fotoapparat.result.PendingResult.access$100(PendingResult.java:20)
       at io.fotoapparat.result.PendingResult$2.run(PendingResult.java:98)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.util.concurrent.ExecutionException: java.lang.RuntimeException: takePicture failed
       at java.util.concurrent.FutureTask.report(FutureTask.java:94)
       at java.util.concurrent.FutureTask.get(FutureTask.java:164)
       at io.fotoapparat.result.PendingResult$1.call(PendingResult.java:56)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.RuntimeException: takePicture failed
       at android.hardware.Camera.native_takePicture(Camera.java)
       at android.hardware.Camera.takePicture(Camera.java:1492)
       at io.fotoapparat.hardware.v1.Camera1.takePicture(Camera1.java:277)
       at io.fotoapparat.routine.picture.TakePictureTask$1.call(TakePictureTask.java:24)
       at io.fotoapparat.routine.picture.TakePictureTask$1.call(TakePictureTask.java:19)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by dmitry-zaitsev** [comment]
This crash typically happens when you are trying to take a picture while the previous image is still being processed. Would it be possible for you to share stacktraces of other threads at the moment of crash? Both Crashlytics and Google Play provide this information.
